# Generated by Django 5.0.4 on 2026-04-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (ascending)')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='teaching.category')),
            ],
            options={
                'verbose_name': 'Sub-Category',
                'verbose_name_plural': 'Sub-Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=520, unique=True)),
                ('body_html', models.TextField(blank=True, help_text='Rich HTML content. Hotspot terms should be wrapped in <span class="hotspot" data-media-id="X">.</span>')),
                ('introduction', models.TextField(blank=True, help_text='HTML for the Introduction accordion panel')),
                ('detailed_explanation', models.TextField(blank=True, help_text='HTML for the Detailed Explanation accordion panel')),
                ('additional_resources', models.TextField(blank=True, help_text='HTML for the Additional Resources accordion panel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='teaching.subcategory')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['sub_category__category__order', 'sub_category__order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text="Display label shown on the hotspot button (e.g. 'স্বর্ণ', 'Audio')", max_length=200)),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('local_video', 'Local Video'), ('youtube', 'YouTube')], max_length=20)),
                ('text_content', models.TextField(blank=True, help_text='Formatted text or definition (TEXT type)', null=True)),
                ('media_file', models.FileField(blank=True, help_text='Uploaded file for image, audio, or local video', null=True, upload_to='media_content/%Y/%m/')),
                ('static_path', models.CharField(blank=True, help_text="Path relative to STATIC_URL for bundled demo assets (e.g. 'demo/rose.jpg')", max_length=500)),
                ('youtube_url', models.URLField(blank=True, help_text='Full YouTube URL (e.g. https://www.youtube.com/watch?v=xxxxx)', null=True)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for image/video', max_length=500)),
                ('is_dashboard', models.BooleanField(default=False, help_text='If True, this item appears as a demo button in the Multimedia Content Examples panel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_contents', to='teaching.subject')),
            ],
            options={
                'verbose_name': 'Media Content',
                'verbose_name_plural': 'Media Contents',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Exact term string as it appears in the article', max_length=200)),
                ('media_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_links', to='teaching.mediacontent')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='teaching.subject')),
            ],
            options={
                'verbose_name': 'Hotspot',
                'verbose_name_plural': 'Hotspots',
                'ordering': ['id'],
            },
        ),
    ]
